all:
	g++ -lncurses main.cpp character.cpp drawable.cpp world.cpp scenery.cpp dialog.cpp scene.cpp trigger.cpp hero.cpp weapon.cpp enemy.cpp fist.cpp pistol.cpp fireball.cpp elecball.cpp projectile.cpp -o game
clean:
	rm -rf *o game.o
